/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Dell\\Desktop\\vuepress-starter\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-37ce52cf",
    path: "/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37ce52cf").then(next)
    },
  },
  {
    path: "/ES6/index.html",
    redirect: "/ES6/"
  },
  {
    name: "v-71c6b697",
    path: "/Javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c6b697").then(next)
    },
  },
  {
    path: "/Javascript/index.html",
    redirect: "/Javascript/"
  },
  {
    name: "v-64697814",
    path: "/Javascript/base_data_type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64697814").then(next)
    },
  },
  {
    name: "v-2f5ece64",
    path: "/Javascript/bom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f5ece64").then(next)
    },
  },
  {
    name: "v-77f4cd18",
    path: "/Javascript/class.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77f4cd18").then(next)
    },
  },
  {
    name: "v-a7598598",
    path: "/Javascript/ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7598598").then(next)
    },
  },
  {
    name: "v-f64b091c",
    path: "/Javascript/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f64b091c").then(next)
    },
  },
  {
    name: "v-02d3ce60",
    path: "/Javascript/dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02d3ce60").then(next)
    },
  },
  {
    name: "v-54ff96b0",
    path: "/Javascript/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54ff96b0").then(next)
    },
  },
  {
    name: "v-492e9598",
    path: "/Javascript/function.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-492e9598").then(next)
    },
  },
  {
    name: "v-73d30294",
    path: "/Javascript/event_loop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73d30294").then(next)
    },
  },
  {
    name: "v-e94f2e24",
    path: "/Javascript/inherit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e94f2e24").then(next)
    },
  },
  {
    name: "v-446b4f58",
    path: "/Javascript/execution_context.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-446b4f58").then(next)
    },
  },
  {
    name: "v-3a8269f4",
    path: "/Javascript/localstore.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a8269f4").then(next)
    },
  },
  {
    name: "v-92deaa58",
    path: "/Javascript/memory_reclamation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92deaa58").then(next)
    },
  },
  {
    name: "v-60c31758",
    path: "/Javascript/object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60c31758").then(next)
    },
  },
  {
    name: "v-6569eab4",
    path: "/Javascript/operator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6569eab4").then(next)
    },
  },
  {
    name: "v-0de9f1a0",
    path: "/Javascript/prototype.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de9f1a0").then(next)
    },
  },
  {
    name: "v-18e39a6c",
    path: "/Javascript/process_control.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18e39a6c").then(next)
    },
  },
  {
    name: "v-4b2bf818",
    path: "/Javascript/render.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b2bf818").then(next)
    },
  },
  {
    name: "v-386b3797",
    path: "/Typescript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-386b3797").then(next)
    },
  },
  {
    path: "/Typescript/index.html",
    redirect: "/Typescript/"
  },
  {
    name: "v-4178f458",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4178f458").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-65ddce93",
    path: "/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65ddce93").then(next)
    },
  },
  {
    path: "/Vue/index.html",
    redirect: "/Vue/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]