/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Cyberloafing Journal",
  "description": "Cyberloafing Journal",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "shortcut icon",
        "type": "image/x-icon",
        "href": "/assets/img/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "ES6+",
      "frontmatter": {},
      "regularPath": "/ES6/",
      "relativePath": "ES6/README.md",
      "key": "v-37ce52cf",
      "path": "/ES6/"
    },
    {
      "title": "JavaScript系统学习指南",
      "frontmatter": {},
      "regularPath": "/Javascript/",
      "relativePath": "Javascript/README.md",
      "key": "v-71c6b697",
      "path": "/Javascript/"
    },
    {
      "title": "基本数据类型",
      "frontmatter": {},
      "regularPath": "/Javascript/base_data_type.html",
      "relativePath": "Javascript/base_data_type.md",
      "key": "v-64697814",
      "path": "/Javascript/base_data_type.html",
      "headers": [
        {
          "level": 2,
          "title": "String",
          "slug": "string"
        },
        {
          "level": 2,
          "title": "Number",
          "slug": "number"
        },
        {
          "level": 2,
          "title": "Boolean",
          "slug": "boolean"
        },
        {
          "level": 2,
          "title": "Null & Undefined",
          "slug": "null-undefined"
        },
        {
          "level": 2,
          "title": "数据类型查询",
          "slug": "数据类型查询"
        },
        {
          "level": 2,
          "title": "包装类的概念",
          "slug": "包装类的概念"
        },
        {
          "level": 2,
          "title": "数据类型转换",
          "slug": "数据类型转换"
        },
        {
          "level": 3,
          "title": "转string",
          "slug": "转string"
        },
        {
          "level": 3,
          "title": "转number",
          "slug": "转number"
        },
        {
          "level": 3,
          "title": "转Boolean",
          "slug": "转boolean"
        }
      ]
    },
    {
      "title": "Bom",
      "frontmatter": {},
      "regularPath": "/Javascript/bom.html",
      "relativePath": "Javascript/bom.md",
      "key": "v-2f5ece64",
      "path": "/Javascript/bom.html"
    },
    {
      "title": "类",
      "frontmatter": {},
      "regularPath": "/Javascript/class.html",
      "relativePath": "Javascript/class.md",
      "key": "v-77f4cd18",
      "path": "/Javascript/class.html"
    },
    {
      "title": "Ajax",
      "frontmatter": {},
      "regularPath": "/Javascript/ajax.html",
      "relativePath": "Javascript/ajax.md",
      "key": "v-a7598598",
      "path": "/Javascript/ajax.html"
    },
    {
      "title": "数组",
      "frontmatter": {},
      "regularPath": "/Javascript/array.html",
      "relativePath": "Javascript/array.md",
      "key": "v-f64b091c",
      "path": "/Javascript/array.html"
    },
    {
      "title": "Dom",
      "frontmatter": {},
      "regularPath": "/Javascript/dom.html",
      "relativePath": "Javascript/dom.md",
      "key": "v-02d3ce60",
      "path": "/Javascript/dom.html"
    },
    {
      "title": "事件",
      "frontmatter": {},
      "regularPath": "/Javascript/event.html",
      "relativePath": "Javascript/event.md",
      "key": "v-54ff96b0",
      "path": "/Javascript/event.html"
    },
    {
      "title": "函数",
      "frontmatter": {},
      "regularPath": "/Javascript/function.html",
      "relativePath": "Javascript/function.md",
      "key": "v-492e9598",
      "path": "/Javascript/function.html"
    },
    {
      "title": "事件循环",
      "frontmatter": {},
      "regularPath": "/Javascript/event_loop.html",
      "relativePath": "Javascript/event_loop.md",
      "key": "v-73d30294",
      "path": "/Javascript/event_loop.html"
    },
    {
      "title": "继承",
      "frontmatter": {},
      "regularPath": "/Javascript/inherit.html",
      "relativePath": "Javascript/inherit.md",
      "key": "v-e94f2e24",
      "path": "/Javascript/inherit.html"
    },
    {
      "title": "执行上下文",
      "frontmatter": {},
      "regularPath": "/Javascript/execution_context.html",
      "relativePath": "Javascript/execution_context.md",
      "key": "v-446b4f58",
      "path": "/Javascript/execution_context.html"
    },
    {
      "title": "本地缓存",
      "frontmatter": {},
      "regularPath": "/Javascript/localstore.html",
      "relativePath": "Javascript/localstore.md",
      "key": "v-3a8269f4",
      "path": "/Javascript/localstore.html"
    },
    {
      "title": "内存回收机制",
      "frontmatter": {},
      "regularPath": "/Javascript/memory_reclamation.html",
      "relativePath": "Javascript/memory_reclamation.md",
      "key": "v-92deaa58",
      "path": "/Javascript/memory_reclamation.html"
    },
    {
      "title": "对象",
      "frontmatter": {},
      "regularPath": "/Javascript/object.html",
      "relativePath": "Javascript/object.md",
      "key": "v-60c31758",
      "path": "/Javascript/object.html"
    },
    {
      "title": "运算符",
      "frontmatter": {},
      "regularPath": "/Javascript/operator.html",
      "relativePath": "Javascript/operator.md",
      "key": "v-6569eab4",
      "path": "/Javascript/operator.html",
      "headers": [
        {
          "level": 2,
          "title": "算数运算符",
          "slug": "算数运算符"
        },
        {
          "level": 3,
          "title": "取模",
          "slug": "取模"
        },
        {
          "level": 2,
          "title": "一元运算符",
          "slug": "一元运算符"
        },
        {
          "level": 2,
          "title": "自增、自减运算符",
          "slug": "自增、自减运算符"
        },
        {
          "level": 3,
          "title": "写在变量前",
          "slug": "写在变量前"
        },
        {
          "level": 3,
          "title": "写在变量后",
          "slug": "写在变量后"
        },
        {
          "level": 2,
          "title": "逻辑运算符",
          "slug": "逻辑运算符"
        },
        {
          "level": 3,
          "title": "非运算符",
          "slug": "非运算符"
        },
        {
          "level": 3,
          "title": "与运算符",
          "slug": "与运算符"
        },
        {
          "level": 3,
          "title": "或运算符",
          "slug": "或运算符"
        },
        {
          "level": 2,
          "title": "赋值运算符",
          "slug": "赋值运算符"
        },
        {
          "level": 2,
          "title": "关系运算符",
          "slug": "关系运算符"
        },
        {
          "level": 2,
          "title": "比较运算符",
          "slug": "比较运算符"
        },
        {
          "level": 2,
          "title": "三元运算符",
          "slug": "三元运算符"
        },
        {
          "level": 2,
          "title": "运算符的优先级",
          "slug": "运算符的优先级"
        }
      ]
    },
    {
      "title": "原型",
      "frontmatter": {},
      "regularPath": "/Javascript/prototype.html",
      "relativePath": "Javascript/prototype.md",
      "key": "v-0de9f1a0",
      "path": "/Javascript/prototype.html"
    },
    {
      "title": "流程控制语句",
      "frontmatter": {},
      "regularPath": "/Javascript/process_control.html",
      "relativePath": "Javascript/process_control.md",
      "key": "v-18e39a6c",
      "path": "/Javascript/process_control.html",
      "headers": [
        {
          "level": 2,
          "title": "if语句",
          "slug": "if语句"
        },
        {
          "level": 2,
          "title": "switch 语句",
          "slug": "switch-语句"
        },
        {
          "level": 3,
          "title": "default关键字",
          "slug": "default关键字"
        },
        {
          "level": 3,
          "title": "case的穿透性",
          "slug": "case的穿透性"
        },
        {
          "level": 2,
          "title": "while循环",
          "slug": "while循环"
        },
        {
          "level": 3,
          "title": "死循环",
          "slug": "死循环"
        },
        {
          "level": 2,
          "title": "do-while循环",
          "slug": "do-while循环"
        },
        {
          "level": 2,
          "title": "for循环",
          "slug": "for循环"
        },
        {
          "level": 3,
          "title": "嵌套for循环",
          "slug": "嵌套for循环"
        },
        {
          "level": 2,
          "title": "break & continue",
          "slug": "break-continue"
        }
      ]
    },
    {
      "title": "浏览器渲染机制",
      "frontmatter": {},
      "regularPath": "/Javascript/render.html",
      "relativePath": "Javascript/render.md",
      "key": "v-4b2bf818",
      "path": "/Javascript/render.html"
    },
    {
      "title": "typescript",
      "frontmatter": {},
      "regularPath": "/Typescript/",
      "relativePath": "Typescript/README.md",
      "key": "v-386b3797",
      "path": "/Typescript/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/logo.png",
        "actionText": "网上冲浪 →",
        "actionLink": "/Javascript/",
        "footer": "MIT Licensed | Copyright © 2018-present Reeyc"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4178f458",
      "path": "/"
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/Vue/",
      "relativePath": "Vue/README.md",
      "key": "v-65ddce93",
      "path": "/Vue/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Javascript",
        "link": "/Javascript/"
      },
      {
        "text": "ES6+",
        "link": "/ES6/"
      },
      {
        "text": "Vue",
        "link": "/Vue/"
      },
      {
        "text": "Typescript",
        "link": "/Typescript/"
      }
    ],
    "sidebar": {
      "sidebarDepth": 2,
      "/Javascript/": [
        {
          "title": "Javascript基础",
          "collapsable": false,
          "children": [
            "/Javascript/base_data_type",
            "/Javascript/operator",
            "/Javascript/process_control",
            "/Javascript/object",
            "/Javascript/function",
            "/Javascript/array",
            "/Javascript/dom",
            "/Javascript/event",
            "/Javascript/bom",
            "/Javascript/ajax",
            "/Javascript/localstore"
          ]
        },
        {
          "title": "Javascript进阶",
          "collapsable": false,
          "children": [
            "/Javascript/prototype",
            "/Javascript/class",
            "/Javascript/inherit",
            "/Javascript/execution_context",
            "/Javascript/event_loop",
            "/Javascript/memory_reclamation",
            "/Javascript/render"
          ]
        }
      ]
    }
  }
}